version: '3.8'

services:
  db:
    image: postgres:13.6
    restart: always
    environment:
      POSTGRES_PASSWORD: ''
      POSTGRES_USER: 'postgres'
      POSTGRES_HOST_AUTH_METHOD: 'trust'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "7432:5432"

  # blockscout:
  #   depends_on:
  #     - db
  #   image: blockscout/blockscout:${DOCKER_TAG:-latest}
  #   restart: always
  #   links:
  #     - db:database
  #   command: 'mix do ecto.drop, ecto.create, ecto.migrate, phx.server'
  #   extra_hosts:
  #     - 'host.docker.internal:host-gateway'
  #   #env_file:
  #   #  -  ./envs/common-blockscout.env
  #   environment:
  #     ETHEREUM_JSONRPC_VARIANT: 'geth'
  #     BLOCK_TRANSFORMER: 'clique'
  #     ETHEREUM_JSONRPC_HTTP_URL: http://202.143.111.229:32003/
  #     DATABASE_URL: postgresql://postgres:@host.docker.internal:7432/blockscout?ssl=false
  #     # ECTO_USE_SSL: false
  #   ports:
  #     - "3000:3000"